### ISSUE TITLE
Gulp Build no longer works

### ISSUE THREAD

**Issue by iStryker** [forumone/gesso#303]
https://github.com/forumone/gesso/commit/26adffadd600d5fba42ba89d16b5f62fb44dac27 broke build

const stat = fs.promises.stat;
                         ^
TypeError: Cannot read property 'stat' of undefined
    at Object.<anonymous> (/home/vagrant/gesso/lib/lintPatternLab.js:7:26)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/vagrant/gesso/gulpfile.js:24:24)
    at Module._compile (module.js:653:30)

const readFile = fs.promises.readFile;
                             ^
TypeError: Cannot read property 'readFile' of undefined
    at Object.<anonymous> (/home/vagrant/gesso/lib/lintPatternLab.js:8:30)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/vagrant/gesso/gulpfile.js:24:24)
    at Module._compile (module.js:653:30)

**Comment by gustavderdrache** [comment]
The `fs.promises` API is available in Node >= 10.0, so it may just be that you need a newer version of Node. (For what it's worth, the [`Dockerfile`](https://github.com/forumone/gesso/blob/8.x-3.x/Dockerfile#L3) in the repository uses the current LTS - Node 12.x.)

**Comment by iStryker** [comment]
Upgrading to Node 12.x fix the problem
