### ISSUE TITLE
Storybook JS error

### ISSUE THREAD

**Issue by dcmouyard** [forumone/gesso#807]
I get the following error when I set “show_admin_info” to true on https://forumone.github.io/gesso/?path=/story/pages-page--page:

```
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Mi (https://forumone.github.io/gesso/4565.315eca10.iframe.bundle.js:476:657206)
    at Sj (https://forumone.github.io/gesso/4565.315eca10.iframe.bundle.js:476:670340)
    at exports.unstable_runWithPriority (https://forumone.github.io/gesso/4565.315eca10.iframe.bundle.js:476:718123)
    at cg (https://forumone.github.io/gesso/4565.315eca10.iframe.bundle.js:476:615767)
    at Jj (https://forumone.github.io/gesso/4565.315eca10.iframe.bundle.js:476:668219)
    at yj (https://forumone.github.io/gesso/4565.315eca10.iframe.bundle.js:476:664426)
    at https://forumone.github.io/gesso/4565.315eca10.iframe.bundle.js:476:616058
    at exports.unstable_runWithPriority (https://forumone.github.io/gesso/4565.315eca10.iframe.bundle.js:476:718123)
    at cg (https://forumone.github.io/gesso/4565.315eca10.iframe.bundle.js:476:615767)
    at fg (https://forumone.github.io/gesso/4565.315eca10.iframe.bundle.js:476:616003)
```

**Comment by dcmouyard** [comment]
This error occurs if `show_footer` is set to false in the page template, but not if set to true.

**Comment by coreylafferty** [comment]
This is fixed in https://github.com/forumone/gesso/pull/830
